### ISSUE TITLE
 Error when I try to start

### ISSUE THREAD

**Issue by Pasquale91** [jpopesculian/soli#2]
any suggestions?

`thread 'main' panicked at 'Solc version unavailable: Io(SolcIoError { io: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: "solc" })', src/main.rs:1154:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

`thread 'main' panicked at 'Solc version unavailable: Io(SolcIoError { io: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: "solc" })', src/main.rs:1154:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: soli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Comment by piesrtasty** [comment]
I am also experiencing this issue. Running on an M1 Mac - OS 12.4 Monterey

**Comment by altfd** [comment]
facing the same issue. M1 Mac - Ventura

**Comment by merklefruit** [comment]
> any suggestions?
> 
> `thread 'main' panicked at 'Solc version unavailable: Io(SolcIoError { io: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: "solc" })', src/main.rs:1154:40 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
> 
> `thread 'main' panicked at 'Solc version unavailable: Io(SolcIoError { io: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: "solc" })', src/main.rs:1154:40 stack backtrace: 0: rust_begin_unwind at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5 1: core::panicking::panic_fmt at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14 2: core::result::unwrap_failed at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5 3: soli::main note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

I'm not on M1 Mac, but perhaps you haven't installed the solidity compiler?

Try to run `solc` on your terminal. If it's not installed, you can add it like explained in the solidity docs: https://docs.soliditylang.org/en/v0.8.14/installing-solidity.html

```
brew update
brew upgrade
brew tap ethereum/ethereum
brew install solidity
```

Try to run `soli` again after installation is complete.

**Comment by Pasquale91** [comment]
> > any suggestions?
> > `thread 'main' panicked at 'Solc version unavailable: Io(SolcIoError { io: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: "solc" })', src/main.rs:1154:40 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
> > `thread 'main' panicked at 'Solc version unavailable: Io(SolcIoError { io: Os { code: 2, kind: NotFound, message: "No such file or directory" }, path: "solc" })', src/main.rs:1154:40 stack backtrace: 0: rust_begin_unwind at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5 1: core::panicking::panic_fmt at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14 2: core::result::unwrap_failed at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5 3: soli::main note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`
> 
> I'm not on M1 Mac, but perhaps you haven't installed the solidity compiler?
> 
> Try to run `solc` on your terminal. If it's not installed, you can add it like explained in the solidity docs: https://docs.soliditylang.org/en/v0.8.14/installing-solidity.html
> 
> ```
> brew update
> brew upgrade
> brew tap ethereum/ethereum
> brew install solidity
> ```
> 
> Try to run `soli` again after installation is complete.

No, but I'm not on M1 Mac, I try on Intel Mac and Ubuntu, in both I have the same problem, so probably the problem is that I don't have installed solidity. 


Thank you for you help

**Comment by Pasquale91** [comment]
Great! Now Work! 

Thank you

**Comment by piesrtasty** [comment]
Thank you, this resolved it for me as well!
